
BLENDER="C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"
DIST=../dist

all : \
    $(DIST)/testScene.pnct \
    $(DIST)/testScene.scene \

$(DIST)/testScene.scene : testScene.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "testScene.blend:Main" "$(DIST)/testScene.scene"

$(DIST)/testScene.pnct : testScene.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "testScene.blend:Main" "$(DIST)/testScene.pnct" 
